[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"

# Form processing
[forms]
  [forms.contact]
    name = "contact"
    method = "POST"
    action = "/thank-you"
    fields = [
      { name = "name", type = "text", required = true },
      { name = "email", type = "email", required = true },
      { name = "title", type = "text", required = true },
      { name = "organization", type = "text", required = true },
      { name = "interest", type = "select", required = true },
      { name = "message", type = "textarea", required = false }
    ]